services:
  db:
    image: postgres:16-alpine
    privileged: true
    ports:
      - 5432:5432
    volumes:
      - .postgresql_data:/var/lib/postgresql/data
    container_name: todoapp-db
    hostname: todoapp-db
    networks:
      - network2
    environment:
      MIX_ENV: dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # ports:
    #   - 4000:4000
    volumes:
      - ./priv/repo/migrations:/app/priv/repo/migrations
      - ./lib:/app/lib
      - ./_docker_build:/code/_build
    container_name: todoapp-api
    # hostname: todoapp-api
    network_mode: host
    environment:
      MIX_ENV: dev
      DATABASE_HOSTNAME: todoapp-db
    # networks:
    #   - network2
    depends_on:
      - db

volumes:
  postgresql_data:
    name: postgresql_data

networks:
  network2:
    name: network2
